---

# ####### Start of Project Definitions  ############## #

- name: define OCP Project for Decision Manager
  set_fact:
    rhdm_ocp_project: "rhdm-{{lab_name}}-{{guid}}"

- name: define OCP Project for RH-SSO
  set_fact:
    rhsso_ocp_project: "rhsso-{{lab_name}}-{{guid}}"

- name: define OCP Project for Fuse Online
  set_fact:
    fuseonline_ocp_project: "fuseonline-{{lab_name}}-{{guid}}"

- name: define OCP Project for NodeJS
  set_fact:
    nodejs_ocp_project: "nodejs-{{lab_name}}-{{guid}}"

- name: define OCP Project for 3scale Gateway
  set_fact:
    threescalegw_ocp_project: "{{ocp_username}}-gw-{{lab_name}}-{{guid}}"

- name: define OCP Project for 3scale MT
  set_fact:
    threescalemt_ocp_project: "3scale-mt-{{lab_name}}-{{guid}}"

# ####### End of Project Definitions ############## #

# ####### Start of Installation of ephemeral RHSSO  ############## #

- name: check if ephemeral RHSSO is deployed
  shell: "oc get project {{rhsso_ocp_project}}"
  register: rhsso_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{rhsso_ocp_project}}"
  shell: "oc new-project {{rhsso_ocp_project}} --display-name={{rhsso_ocp_project}} --description={{ocp_username}}"
  when: rhsso_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{rhsso_ocp_project}} AAD='{{guid}}'"
  when: rhsso_project_result is failed

- name: "Make sure we go back to project {{rhsso_ocp_project}}"
  shell: "oc project {{rhsso_ocp_project}}"
  when: rhsso_project_result is failed

- name: Create SSO Service Account
  shell: "oc create serviceaccount sso-service-account"
  when: rhsso_project_result is failed

- name: Give service account access to Lab Infra project
  shell: "oc policy add-role-to-user view system:serviceaccount:{{ocp_username}}-sso:sso-service-account"
  when: rhsso_project_result is failed

- name: Create ephemeral RHSSO template
  shell: "oc create -f {{rhsso_template_yml}} -n {{rhsso_ocp_project}}"
  when: rhsso_project_result is failed

- name: Create ephemeral RHSSO app
  shell: "oc new-app --template=sso72-x509-https --param HOSTNAME_HTTP={{ocp_username}}-sso-unsecured.{{$OCP_SUFFIX}} --param HOSTNAME_HTTPS={{ocp_username}}-sso.{{$OCP_SUFFIX}} --param SSO_ADMIN_USERNAME=admin --param SSO_ADMIN_PASSWORD=password --param SSO_SERVICE_USERNAME=admin --param SSO_SERVICE_PASSWORD=password --param SSO_REALM=3scaleRealm -n {{rhsso_ocp_project}}"
  when: rhsso_project_result is failed

# ####### End of Installation of ephemeral RHSSO  ############## #

# ###### Start of Installation of Fuse Online ########## #

- name: check if Fuse Online is deployed
  shell: "oc get project {{fuseonline_ocp_project}}"
  register: fuseonline_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{fuseonline_ocp_project}}"
  shell: "oc new-project {{fuseonline_ocp_project}} --display-name={{fuseonline_ocp_project}} --description={{ocp_username}}"
  when: fuseonline_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{fuseonline_ocp_project}} AAD='{{guid}}'"
  when: fuseonline_project_result is failed

- name: "Make sure we go back to project {{fuseonline_ocp_project}}"
  shell: "oc project {{fuseonline_ocp_project}}"
  when: fuseonline_project_result is failed

- name: Retrieve Fuse Online Installation Script
  get_url:
    url: https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/script/install-syndesis
    dest: /tmp/install-syndesis.sh
    mode: 0755
    owner: opentlc-mgr
  when: fuseonline_project_result is failed

# Deploy Fuse Online.
- name: Run Fuse Online Installation
  shell: "/tmp/install-syndesis.sh --setup"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

- name: Grant access rights to Fuse Online
  shell: "/tmp/install-syndesis.sh --grant {{ocp_username}}"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

- name: Grant access rights to Fuse Online
  shell: "/tmp/install-syndesis.sh --route {{ocp_username}}-fuse-ignite.{{$OCP_SUFFIX}} --open --tag=1.5.4-20180910"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

# ###### End of Installation of Fuse Online ##########

# ###### Start of Creation of NodeJS project ##########

- name: check if NodeJS Project exists
  shell: "oc get project {{nodejs_ocp_project}}"
  register: nodejs_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{nodejs_ocp_project}}"
  shell: "oc new-project {{nodejs_ocp_project}} --display-name={{nodejs_ocp_project}} --description={{ocp_username}}"
  when: nodejs_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{nodejs_ocp_project}} AAD='{{guid}}'"
  when: nodejs_project_result is failed

- name: Create NodeJS template
  shell: oc create -f {{nodejs_template_yml}} -n {{nodejs_ocp_project}}
  when: nodejs_project_result is failed

- name: "Make sure we go back to project {{nodejs_ocp_project}}"
  shell: "oc project {{nodejs_ocp_project}}"
  when: nodejs_project_result is failed

# ###### End of NodeJS Project creation ##########

# ###### Start of 3scale Gateway Project creation ##########

- name: check if 3scale Gateway Project exists
  shell: "oc get project {{threescalegw_ocp_project}}"
  register: threescalegw_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{threescalegw_ocp_project}}"
  shell: "oc new-project {{threescalegw_ocp_project}} --display-name={{threescalegw_ocp_project}} --description={{ocp_username}}"
  when: threescalegw_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{threescalegw_ocp_project}} AAD='{{guid}}'"
  when: threescalegw_project_result is failed

- name: "Make sure we go back to project {{threescalegw_ocp_project}}"
  shell: "oc project {{threescalegw_ocp_project}}"
  when: threescalegw_project_result is failed

- name: "Delete default routes in project {{threescalegw_ocp_project}}"
  shell: "oc delete route --all"
  when: threescalegw_project_result is failed

- name: "Create staging route quote-stage in project {{threescalegw_ocp_project}}"
  shell: "oc create route edge quote-stage --service='stage-apicast' --hostname={{ocp_username}}-quote-stage.{{$OCP_SUFFIX}}"
  when: threescalegw_project_result is failed

- name: "Create staging route quote-prod in project {{threescalegw_ocp_project}}"
  shell: "oc create route edge quote-prod --service='prod-apicast' --hostname={{ocp_username}}-quote-prod.{{$OCP_SUFFIX}}"
  when: threescalegw_project_result is failed

- name: check if project {{threescalemt_ocp_project}} exists
  shell: "oc get project {{threescalemt_ocp_project}}"
  register: threescalemt_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{threescalemt_ocp_project}}"
  shell: "oc new-project {{threescalemt_ocp_project}} --display-name={{threescalemt_ocp_project}} --description={{ocp_username}}"
  when: threescalemt_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{threescalemt_ocp_project}} AAD='{{guid}}'"
  when: threescalemt_project_result is failed

- name: "Make sure we go back to project {{threescalemt_ocp_project}}"
  shell: "oc project {{threescalemt_ocp_project}}"
  when: threescalemt_project_result is failed

- name: "Delete default routes in project {{threescalemt_ocp_project}}"
  shell: "oc delete route --all"
  when: threescalemt_project_result is failed

- name: "Create mt-developer route in project {{threescalemt_ocp_project}}"
  shell: "oc create route edge {{ocp_username}}-3scale-mt-developer --service='system-developer' --hostname={{ocp_username}}-3scale-mt.{{OCP_SUFFIX}}"
  when: threescalemt_project_result is failed

# ###### End of 3scale Gateway Project creation ##########

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
