---
- name: define ocp_project
  set_fact:
    ocp_project: "{{lab_name}}-{{guid}}"

# #########             Constraint project          ##############

- name: Create project; project =  {{ocp_project}}
  shell: "oc new-project {{ocp_project}}"

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{guid}}'"

- name: Give ocp_username access to {{ocp_constraints_project}};  user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: Delete default limitrange
  shell: |
    oc delete limitrange {{ocp_project}}-core-resource-limits -n {{ocp_project}}

- name: Create a new limitrange
  template:
    src: templates/constraints_limitrange.yaml
    dest: /tmp/{{ocp_project}}_limitrange.yaml
- shell: |
    oc create -f /tmp/{{ocp_project}}_limitrange.yaml -n {{ocp_project}}


- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

# ###############################################################

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
