---
- name: Ensure Molecule required packages are installed
  yum:
    name: "{{ molecule_yum_packages }}"
    state: present

- name: Ensure Molecule is installed
  pip:
    name: "{{ molecule_pip_packages }}"
    state: present
