---
ocp_username: dtorresf-redhat.com

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '7Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi
