---
- name: define user ocp_project
  set_fact:
    ocp_project: "istio-system"

- name: Make sure we go back to default project
  shell: "oc project default"



# #######         Istio Control Plane      ############## #

- name: Determine if istio-system namespace already exists.  Provision istio control plane once per OCP cluster
  command: oc get projects -o name
  register: oc_projects
  changed_when: false

- name: "Add anyuid scc to all authenticated: {{oc_projects.stdout_lines}}"
  shell: "oc adm policy add-scc-to-group anyuid system:authenticated -n {{ocp_project}}"
  when: '"projects/" ~ "istio-system" not in oc_projects.stdout_lines'

- name: Copy istio-demo template to known path
  template:
    src: templates/istio-demo-1.0.0.yaml 
    dest: /tmp/istio-demo-1.0.0.yaml
  when: '"projects/" ~ "istio-system" not in oc_projects.stdout_lines'

- name: set ocp_project to istio-system to support wait for deploy
  set_fact:
    ocp_project: istio-system

- name: Provision Istio Control Plane (which creates istio-system namespace)
  shell:  "oc create -f /tmp/istio-demo-1.0.0.yaml"
  when: '"projects/" ~ "istio-system" not in oc_projects.stdout_lines'

# TO-DO:  investigate why this isn't working
- name: wait for istio deployments
  include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - istio-citadel
      - istio-egressgateway
      - istio-galley
      - istio-ingressgateway
      - istio-pilot
      - istio-policy
      - istio-sidecar-injector
      - istio-statsd-prom-bridge
      - istio-telemetry
      - istio-tracing

- name: wait for Istio monitoring UIs
  include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - grafana
      - prometheus
      - servicegraph

- name: Expose routes
  shell: |
      oc expose svc istio-ingressgateway -n istio-system && \ 
      oc expose svc servicegraph -n istio-system && \
      oc expose svc grafana -n istio-system && \
      oc expose svc prometheus -n istio-system && \
      oc expose svc tracing -n istio-system
  when: '"projects/" ~ "istio-system" not in oc_projects.stdout_lines'

###########################################################

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{guid}}'"

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
