---
become_override: false
ocp_username: adm1
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

ocp_apps_domain: "apps.{{subdomain_base}}"

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

SOURCE_REPOSITORY_URL: "https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs"
SOURCE_REPOSITORY_REF: "master"

nodejs_template_yml: "{{SOURCE_REPOSITORY_URL}}/master/templates/nodejs-quoting-app-template.json"
rhsso_template_yml: "{{SOURCE_REPOSITORY_URL}}/master/templates/sso72-x509-https.json"

REGION: "0b11"
OCP_DOMAIN: "rhte.opentlc.com"
OCP_SUFFIX: "apps.{{REGION}}.{{OCP_DOMAIN}}"

# Start and End tenants.
START_TENANT: 1
END_TENANT: 10

OPENSHIFT_MASTER: "https://master.{{REGION}}.{{OCP_DOMAIN}}"
SSO_HOSTNAME_HTTP: "sso-unsecured.{{OCP_SUFFIX}}"
SSO_HOSTNAME_HTTPS: "sso.{{OCP_SUFFIX}}"
APICURIO_UI_ROUTE: "apicurio-studio.{{OCP_SUFFIX}}"
APICURIO_API_ROUTE: "apicurio-studio-api.{{OCP_SUFFIX}}"
APICURIO_WS_ROUTE: "apicurio-studio-ws.{{OCP_SUFFIX}}"
MICROCKS_ROUTE_HOSTNAME: "microcks.{{OCP_SUFFIX}}"
OPENSHIFT_OAUTH_CLIENT_NAME: "laboauth"
KEYCLOAK_ROUTE_HOSTNAME: "{{SSO_HOSTNAME_HTTP}}"

KIE_ADMIN_USER: "admin"
KIE_ADMIN_PWD: "password"
KIE_SERVER_USER: "user"
KIE_SERVER_PWD: "password"
KIE_SERVER_CONTAINER_DEPLOYMENT: "quoting=com.redhat:insuranceQuoting:1.0.1"

lab_name: rhte-mw-api-biz
