---
- name: define ocp_project
  set_fact:
    ocp_project: "{{lab_name}}-{{guid}}"

# #######  Strimzi Installation  ############## #
# Components:
#   1) Kafka
####################################################

- name: Strimzi Installation Tasks Start
  debug:
    msg: Strimzi Installation Tasks Start

- name: define user user2_kafka_project
  set_fact:
    user2_kafka_project: "{{ocp_username}}-{{lab_1_name}}"

- name: "Create project for workload {{lab_1_name}}"
  shell: "oc new-project {{lab_1_name}}"

- name: "Label namespace"
  command: "oc label namespace {{lab_1_name}} AAD='{{guid}}'"

- name: Make sure we go back to default project
  shell: "oc project default"
  
- name: Add user as admin to the project
  shell: "oc adm policy add-role-to-user admin {{ocp_username}} -n {{lab_1_name}}"

- name: delete temp dir if it exists
  file:
      path: /tmp/{{ocp_project}}
      state: absent
- file:
      path: /tmp/{{ocp_project}}
      state: directory

- name: Create SA for strimzi cluster operator
  shell: "oc apply -f {{ serviceaccount_yaml }} -n {{lab_1_name}}"

- name: Create cluster role for strimzi cluster operator
  shell: "oc apply -f {{ clusteroperator_role_yaml }} -n {{lab_1_name}}"

- name: Create cluster role binding for strimzi cluster operator
  shell: "oc apply -f {{ clusteroperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Create cluster role for Kafka broker
  shell: "oc apply -f {{ kafkabroker_role_yaml }} -n {{lab_1_name}}"

- name: Create cluster role binding for strimzi-cluster-operator-topic-operator-delegation
  shell: ""

- name: Create cluster role for strimzi-topic operator
  shell: "oc apply -f {{ topicoperator_SOMETHING_yaml }} -n {{lab_1_name}}"

- name: Create  cluster role binding for strimzi-cluster-operator-topic-operator-delegation
  shell: "oc apply -f {{ topicoperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka
  shell: "oc apply -f {{ kafka_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka connect
  shell: "oc apply -f {{ kafkaconnect_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka connect s2i
  shell: "oc apply -f {{ kafkaconnects2i_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka topic
  shell: "oc apply -f {{ kafkatopic_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka user
  shell: "oc apply -f {{ kafkauser_crd_yaml }} -n {{lab_1_name}}"
  
- name: Deploy Kafka
  shell: "oc apply -f examples/install/cluster-operator/05-Deployment-strimzi-cluster-operator.yaml -n {{lab_1_name}}"

- name: Apply Kafka Persistent template
  shell: "oc apply -f {{ kafkapersistent_yaml }} -n {{lab_1_name}}"

- name: Create Kafka topics
  shell: "oc apply -f {{ kafkatopic_yaml }} -n {{lab_1_name}}"

- name: Create Kafka users
  shell: "oc apply -f {{ kafkauser_yaml }} -n {{lab_1_name}}"

- name: Annotate the empty project as requested by user [what does this do?]
  shell: "oc annotate namespace {{lab_1_name}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Strimzi Installation Tasks Complete
  debug:
    msg: Strimzi Installation Tasks Complete

- name: Lab 6 Op Intel Installation workload Tasks Complete
  debug:
    msg: Lab 6 Op Intel Installation workload Tasks Complete
