---
- name: post_workload Tasks Complete
  debug:
    msg: "Pre-Software checks completed successfully - Removed"

- name: define ocp_project
  set_fact:
    ocp_project: "rh-sso-{{guid}}"

- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}-{{guid}}"
  shell: oc delete clusterresourcequota clusterquota-{{ocp_username}}-{{guid}}
  ignore_errors: true

- name: Remove any lingering tmp files
  shell: "rm -rf /tmp/{{guid}}"

- name: Remove user Project
  shell: "oc delete project {{ocp_project}}"

- name: Remove istio-system Project
  shell: "oc delete project istio-system"
  ignore_errors: true

#- name: clean up residual istio stuff
#  template:
#    src: templates/istio_cleanup.sh
#    dest: /tmp/istio_cleanup.sh
#    mode: 0755
#- shell:  "/tmp/istio_cleanup.sh"

- name: Delete Istio Control Plane
  shell:  "oc delete -f /tmp/istio-demo-1.0.0.yaml"
  ignore_errors: true


- name: post_workload Tasks Complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
