---

# Red Hat SSO 7.2
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/sso72-x509-mysql-persistent.json -n openshift

#Red Hat SSO 7.2 Ephimeral
#oc create -f https://raw.githubusercontent.com/pszuster/3ScaleTD/master/templates/sso72-x509-https.json

- name: define ocp_project
  set_fact:
    ocp_project: "rh-sso-{{guid}}"
- name: "Create project for workload {{ocp_project}}"
  shell: "oc new-project {{ocp_project}}"

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{guid}}'"

- name: Make sure we go back to default project
  shell: "oc project default"
  
- name: define sso template version
  set_fact:
    sso_version: "ose-v1.4.15"
- name: Make sure use shared namespace
  shell: "oc project {{ocp_project}}"
- name: Create service accounts and secrets for RH SSO
  shell: "oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/{{sso_version}}/secrets/sso-app-secret.json -n {{ocp_project}}"
- name: Add cluster view policy to sa for clustering
  shell: "oc policy add-role-to-user view system:serviceaccount:{{ocp_project}}:sso-service-account -n {{ocp_project}}"
- name: Import RH SSO template
  shell: "oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/{{sso_version}}/sso/sso72-mysql-persistent.json"
- name: Create RH SSO app
  shell: "oc new-app sso72-mysql-persistent -p HTTPS_NAME=jboss -p HTTPS_PASSWORD=mykeystorepass -p SSO_ADMIN_USERNAME=keyadmin \
  -p SSO_ADMIN_PASSWORD=keypassword -n {{ocp_project}}"
- name: Wait for Red Hat SSO to be running
  command: "oc get dc/sso -o yaml -n {{ocp_project}}"
  register: result
  until: '"availableReplicas: 1" in result.stdout'
  retries: 5
  delay: 60
  changed_when: false

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
